"""PCAP Template Module for generating various traffic patterns."""

from .pcap_templates import (
    TEMPLATE_REGISTRY,
    create_normal_web_browsing_schema,
    create_normal_api_calls_schema,
    create_normal_ssh_session_schema,
    create_normal_file_transfer_schema,
    create_normal_database_query_schema,
    create_normal_email_schema,
    create_anomaly_port_scan_schema,
    create_anomaly_syn_flood_schema,
    create_anomaly_large_upload_schema,
    create_anomaly_beaconing_schema,
    create_anomaly_dns_tunnel_schema,
    create_anomaly_slow_loris_schema,
    create_suspicious_brute_force_schema,
    create_suspicious_lateral_movement_schema,
    create_suspicious_data_staging_schema,
    create_suspicious_encrypted_tunnel_schema,
    create_suspicious_protocol_anomaly_schema,
    get_template,
    list_templates,
)

__all__ = [
    "TEMPLATE_REGISTRY",
    "create_normal_web_browsing_schema",
    "create_normal_api_calls_schema",
    "create_normal_ssh_session_schema",
    "create_normal_file_transfer_schema",
    "create_normal_database_query_schema",
    "create_normal_email_schema",
    "create_anomaly_port_scan_schema",
    "create_anomaly_syn_flood_schema",
    "create_anomaly_large_upload_schema",
    "create_anomaly_beaconing_schema",
    "create_anomaly_dns_tunnel_schema",
    "create_anomaly_slow_loris_schema",
    "create_suspicious_brute_force_schema",
    "create_suspicious_lateral_movement_schema",
    "create_suspicious_data_staging_schema",
    "create_suspicious_encrypted_tunnel_schema",
    "create_suspicious_protocol_anomaly_schema",
    "get_template",
    "list_templates",
]
